In [1]:
1+1

2

MARK DOWN 관련  

# HEADING1
## HEADING2
### HEADING3
#### HEADING4
##### HEADING5



LINE NUBER DISPLAY  
----------------------------------

1111111  
__2222222__  
**3333333**  

* chapter1
* chapter2

[파이썬으로 배우는 알고리즘 트레이딩](https://wikidocs.net/2818)  
배우는 것에서 그치지말고 실생활에서 활용할수있는 것으로까지

```Programming Python ```

In [2]:
2**3

8

In [3]:
[2,3,4]

[2, 3, 4]

In [4]:
sum([2,3,4])

9

In [5]:
import pandas as pd
bike = pd.read_csv("bike_rental.csv")

In [6]:
"a" + "b" + "c"

'abc'

In [7]:
"aa" * 3

'aaaaaa'

In [8]:
print('hello!?')

hello!?


In [10]:
# print('It's great!')

In [11]:
"column_" + str(1)

'column_1'

In [12]:
print("\a")




In [13]:
tx = "Hello!"
print(tx[0])
print(tx[3])
print(tx[0:4])

print(tx[-1])
print(tx[-3])
print(tx[2:])
print(tx[:2])

H
l
Hell
!
l
llo!
He


In [14]:
aa = [1, 2, 3]
bb = [4, 5, 6]
print(aa + bb)
print(aa * 2)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]


In [15]:
aa = [1,2,3]
print(aa[0])
print(aa[1:3])
print(aa[1:])
print(aa[:2])

1
[2, 3]
[2, 3]
[1, 2]


In [16]:
bb = [1,2, ["a", "b", "c"]]
print(bb[0])
print(bb[2][1:3])

1
['b', 'c']


In [17]:
aa = [1,2,3]
aa[0] = 55
print(aa)

[55, 2, 3]


In [18]:
bb = [2, 3, 4]
bb[2] = [99, 99]
print(bb)

[2, 3, [99, 99]]


In [19]:
cc = [3,4,5]
cc[1:2] = [99, 99]
print(cc)

[3, 99, 99, 5]


In [20]:
dd = [4, 5, 6]
dd[2:2] = [99, 99]
print(dd)

[4, 5, 99, 99, 6]


In [21]:
kk = [1,2,3]
del kk[0]
print(kk)

[2, 3]


In [22]:
kk = [1,2,3]
del kk[0:2]
print(kk)

[3]


In [23]:
gg = [1, 2, 3]
gg.extend(["a", "b"])
print(gg)

[1, 2, 3, 'a', 'b']


In [24]:
gg = [1, 2, 3]
gg.append(["a", "b"])
print(gg)

[1, 2, 3, ['a', 'b']]


In [25]:
bb = [2, 3, 4]
bb + [99, 99]

[2, 3, 4, 99, 99]

In [26]:
ww = [2, 5, 3]
ww.sort()
print(ww)

[2, 3, 5]


In [27]:
ww.sort(reverse=True)
print(ww)

[5, 3, 2]


In [28]:
pp = [1,2,3]
pp.reverse()
print(pp)

[3, 2, 1]


In [29]:
True + True

2

In [30]:
sum([True, True, False])

2

In [31]:
mm = [1, 2, 3, 2]
#mm.index(1)
#mm.index(2)
mm.index(2)

1

In [32]:
ss = [1, 2, 3]
ss.insert(2, 99)
print(ss)

[1, 2, 99, 3]


In [33]:
ss = [1, 2, 3]
ss.insert(5, 99)
print(ss)

[1, 2, 3, 99]


In [34]:
tt = [1, 2, 3, 2]
tt.remove(2)
print(tt)

[1, 3, 2]


In [35]:
tt = [1, 2, 3, 2]
tt.count(2)

2

In [36]:
print((1, 2, 3))
print((1, 2, (5, 6, 7)))

(1, 2, 3)
(1, 2, (5, 6, 7))


In [37]:
aa = (1, 2, [5,6,7])
aa[2][2] = 2
print(aa)

(1, 2, [5, 6, 2])


In [38]:
dic = {"k1": 1, "k2":"aa", "k3":[1,2,3]}
dic

{'k1': 1, 'k2': 'aa', 'k3': [1, 2, 3]}

In [39]:
dic["k3"]

[1, 2, 3]

In [40]:
dic["k3"][1]

2

In [41]:
import numpy as np
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.zeros_like([2, 4, 5, 6])

array([0, 0, 0, 0])

In [43]:
data = np.array([2, 4, 7, 9.1])
data.ndim

1

In [44]:
data.shape

(4,)

In [45]:
data.dtype

dtype('float64')

In [46]:
a = np.random.randn(100, 100)

In [47]:
%timeit np.dot(a,a)

21.5 µs ± 1.64 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [48]:
%debug?

In [49]:
%pwd

'C:\\Users\\SDS\\Documents'

In [50]:
%magic

In [51]:
%hist

1+1
2**3
[2,3,4]
sum([2,3,4])
import pandas as pd
bike = pd.read_csv("bike_rental.csv")
"a" + "b" + "c"
"aa" * 3
print('hello!?')
print('It's great!')
# print('It's great!')
"column_" + str(1)
print("\a")
tx = "Hello!"
print(tx[0])
print(tx[3])
print(tx[0:4])

print(tx[-1])
print(tx[-3])
print(tx[2:])
print(tx[:2])
aa = [1, 2, 3]
bb = [4, 5, 6]
print(aa + bb)
print(aa * 2)
aa = [1,2,3]
print(aa[0])
print(aa[1:3])
print(aa[1:])
print(aa[:2])
bb = [1,2, ["a", "b", "c"]]
print(bb[0])
print(bb[2][1:3])
aa = [1,2,3]
aa[0] = 55
print(aa)
bb = [2, 3, 4]
bb[2] = [99, 99]
print(bb)
cc = [3,4,5]
cc[1:2] = [99, 99]
print(cc)
dd = [4, 5, 6]
dd[2:2] = [99, 99]
print(dd)
kk = [1,2,3]
del kk[0]
print(kk)
kk = [1,2,3]
del kk[0:2]
print(kk)
gg = [1, 2, 3]
gg.extend(["a", "b"])
print(gg)
gg = [1, 2, 3]
gg.append(["a", "b"])
print(gg)
bb = [2, 3, 4]
bb + [99, 99]
ww = [2, 5, 3]
ww.sort()
print(ww)
ww.sort(reverse=True)
print(ww)
pp = [1,2,3]
pp.reverse()
print(pp)
True + True
sum([True, True, False])
mm 

In [52]:
%matplotlib

Using matplotlib backend: Qt5Agg


In [53]:
%matplotlib inline

In [54]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr_sub = arr[0, 0:2]
arr_sub


array([1, 2])

In [56]:
arr[0, 0:2] = [99, 88]

In [57]:
arr_sub

array([99, 88])

In [58]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr_sub = arr[0, 0:2].copy()
arr_sub

array([1, 2])

In [60]:
arr[0, 0:2] = [99, 88]
arr

array([[99, 88,  3],
       [ 4,  5,  6]])

In [61]:
arr_sub

array([1, 2])

## pandas series

In [62]:
import pandas as pd
ser2 = pd.Series([2,4,7,8], index=["a","b", "c", "d"])
ser2

a    2
b    4
c    7
d    8
dtype: int64

In [63]:
ser2["a"] = 4
ser2

a    4
b    4
c    7
d    8
dtype: int64

In [64]:
ser2["a"]

4

In [65]:
ser2[2:]

c    7
d    8
dtype: int64

In [66]:
ser2["a"] = "asdf"

In [67]:
ser2

a    asdf
b       4
c       7
d       8
dtype: object

In [68]:
values = {"aa" : [1,2,3],
         "bb" : ["a", "b", "c"]}
df = pd.DataFrame(values)
df

aa bb
0   1  a
1   2  b
2   3  c

In [69]:
df = pd.DataFrame(np.arange(6).reshape(3, 2), index=["a", "b", "c"], columns=["aa", "bb"])
df

aa  bb
a   0   1
b   2   3
c   4   5

In [70]:
df["aa"]

a    0
b    2
c    4
Name: aa, dtype: int32

In [71]:
df["aa"][1]

2

In [72]:
df["aa"][:2]

a    0
b    2
Name: aa, dtype: int32

In [73]:
df.columns

Index(['aa', 'bb'], dtype='object')

In [74]:
df.columns[1]

'bb'

In [75]:
df.columns = ["xx", "yy"]
df.columns

Index(['xx', 'yy'], dtype='object')

In [76]:
df = df.rename(columns={"yy": "abs"})
df

xx  abs
a   0    1
b   2    3
c   4    5

In [77]:
df.rename(columns={"yy":"abs"}, inplace=True)

In [78]:
df

xx  abs
a   0    1
b   2    3
c   4    5

## read csv

In [79]:
df = pd.read_csv("AWS_sample.txt", sep= "#")

In [80]:
df.head()

AWS_ID             TM    TA  Wind X.
0     108  2016-07-01 00  24.2   2.3  =
1     108  2016-07-01 01  24.3   2.3  =
2     108  2016-07-01 02  23.7   3.8  =
3     108  2016-07-01 03  23.3   3.0  =
4     108  2016-07-01 04  23.5   2.1  =

In [81]:
df.iloc[:3]

AWS_ID             TM    TA  Wind X.
0     108  2016-07-01 00  24.2   2.3  =
1     108  2016-07-01 01  24.3   2.3  =
2     108  2016-07-01 02  23.7   3.8  =

In [82]:
df2 = pd.read_csv("hotel_booking_train_1m.zip")
df2

date_time  site_name  posa_continent  user_location_country  \
0       2014-07-07         11               3                    205   
1       2014-09-20          2               3                     66   
2       2014-10-23          2               3                     66   
3       2013-11-07         37               1                     69   
4       2013-02-24          2               3                     66   
5       2013-03-01          2               3                     66   
6       2014-08-07         24               2                      3   
7       2014-06-01          2               3                     66   
8       2014-04-14          2               3                    215   
9       2014-08-16          2               3                     12   
10      2014-11-29         24               2                      3   
11      2014-10-30          2               3                     66   
12      2014-12-20         24               2                      3   
13      2014-01-25         23               1                      1   
14      2014-12-19          2               3                     66   
15      2014-11-30         24               2                      3   
16      2014-09-10          2               3                     66   
17      2013-10-31          2               3                     59   
18      2014-08-02         11               3                     66   
19      2014-10-07         37               1                     69   
20      2014-04-20         34               3                    205   
21      2014-11-16          8               4                     77   
22      2014-07-15          2               3                     66   
23      2014-11-12         37               1                     69   
24      2014-11-05          2               3                     66   
25      2014-08-27         24               2                     66   
26      2014-01-15          2               3                     66   
27      2014-08-13         13               1                     46   
28      2014-09-26          2               3                     66   
29      2014-03-30          2               3                     66   
...            ...        ...             ...                    ...   
999970  2014-10-29         11               3                    205   
999971  2014-11-25          2               3                     66   
999972  2014-08-08          2               3                     66   
999973  2014-05-27         34               3                    205   
999974  2014-04-15          2               3                    179   
999975  2013-05-02          2               3                     66   
999976  2013-07-16         37               1                     69   
999977  2014-10-21         37               1                     69   
999978  2014-09-10          2               3                     66   
999979  2014-10-28          2               3                     66   
999980  2014-06-09          2               3                    215   
999981  2013-01-20         24               2                    194   
999982  2013-05-26          2               3                     66   
999983  2014-09-14          2               3                    209   
999984  2014-04-17         32               1                     62   
999985  2014-10-10         37               1                     69   
999986  2014-05-25          2               3                     27   
999987  2013-12-15         34               3                    205   
999988  2014-05-21         37               1                     69   
999989  2013-11-23          8               4                     77   
999990  2014-10-18          2               3                     66   
999991  2014-10-16         37               1                     69   
999992  2014-11-29         13               1                     46   
999993  2013-08-11         37               1    

In [83]:
df2.to_csv("hotel_test.gz", compression="gzip", index=False)

In [84]:
bike_json = pd.read_json("bike.json")
bike_json

atemp  casual  count            datetime  holiday  humidity  \
0      14.395       3     16 2011-01-01 00:00:00        0        81   
1      13.635       8     40 2011-01-01 01:00:00        0        80   
2      13.635       5     32 2011-01-01 02:00:00        0        80   
3      14.395       3     13 2011-01-01 03:00:00        0        75   
4      14.395       0      1 2011-01-01 04:00:00        0        75   
5      12.880       0      1 2011-01-01 05:00:00        0        75   
6      13.635       2      2 2011-01-01 06:00:00        0        80   
7      12.880       1      3 2011-01-01 07:00:00        0        86   
8      14.395       1      8 2011-01-01 08:00:00        0        75   
9      17.425       8     14 2011-01-01 09:00:00        0        76   
10     19.695      12     36 2011-01-01 10:00:00        0        76   
11     16.665      26     56 2011-01-01 11:00:00        0        81   
12     21.210      29     84 2011-01-01 12:00:00        0        77   
13     22.725      47     94 2011-01-01 13:00:00        0        72   
14     22.725      35    106 2011-01-01 14:00:00        0        72   
15     21.970      40    110 2011-01-01 15:00:00        0        77   
16     21.210      41     93 2011-01-01 16:00:00        0        82   
17     21.970      15     67 2011-01-01 17:00:00        0        82   
18     21.210       9     35 2011-01-01 18:00:00        0        88   
19     21.210       6     37 2011-01-01 19:00:00        0        88   
20     20.455      11     36 2011-01-01 20:00:00        0        87   
21     20.455       3     34 2011-01-01 21:00:00        0        87   
22     20.455      11     28 2011-01-01 22:00:00        0        94   
23     22.725      15     39 2011-01-01 23:00:00        0        88   
24     22.725       4     17 2011-01-02 00:00:00        0        88   
25     21.970       1     17 2011-01-02 01:00:00        0        94   
26     21.210       1      9 2011-01-02 02:00:00        0       100   
27     22.725       2      6 2011-01-02 03:00:00        0        94   
28     22.725       2      3 2011-01-02 04:00:00        0        94   
29     21.210       0      2 2011-01-02 06:00:00        0        77   
...       ...     ...    ...                 ...      ...       ...   
10856  19.695      13    525 2012-12-18 18:00:00        0        46   
10857  19.695      19    353 2012-12-18 19:00:00        0        46   
10858  16.665       4    268 2012-12-18 20:00:00        0        50   
10859  17.425       9    168 2012-12-18 21:00:00        0        50   
10860  16.665       5    132 2012-12-18 22:00:00        0        49   
10861  17.425       1     81 2012-12-18 23:00:00        0        49   
10862  15.910       6     41 2012-12-19 00:00:00        0        61   
10863  15.910       1     15 2012-12-19 01:00:00        0        65   
10864  15.150       1      3 2012-12-19 02:00:00        0        65   
10865  13.635       0      5 2012-12-19 03:00:00        0        75   
10866  12.120       1      7 2012-12-19 04:00:00        0        75   
10867  14.395       2     31 2012-12-19 05:00:00        0        75   
10868  12.880       3    112 2012-12-19 06:00:00        0        75   
10869  13.635       3    363 2012-12-19 07:00:00        0        75   
10870  12.880      13    678 2012-12-19 08:00:00        0        87   
10871  14.395       8    317 2012-12-19 09:00:00        0        75   
10872  16.665      17    164 2012-12-19 10:00:00        0        70   
10873  20.455      31    200 2012-12-19 11:00:00        0        54   
10874  20.455      33    236 2012-12-19 12:00:00        0        54   
10875  21.210      30    213 2012-12-19 13:00:00        0        50   
10876  21.210      33    218 2012-12-19 14:00:00        0        50   
10877  21.210      28    237 2012-12-19 15:00:00        0        50   
10878  21.210      37    334 2012-12-19 16:00:00        0        50   
10879  20.455      26    562 2012-12-19 17:00:00        0        50   
10880  19.695      23    569 201

In [85]:
bike.head()

datetime  casual  registered  count
0  2011-01-01 00:00:00       3          13     16
1  2011-01-01 01:00:00       8          32     40
2  2011-01-01 02:00:00       5          27     32
3  2011-01-01 03:00:00       3          10     13
4  2011-01-01 04:00:00       0           1      1

In [86]:
bike.tail(2)

datetime  casual  registered  count
10884  2012-12-19 22:00:00      12         117    129
10885  2012-12-19 23:00:00       4          84     88

In [87]:
bike.head(5)

datetime  casual  registered  count
0  2011-01-01 00:00:00       3          13     16
1  2011-01-01 01:00:00       8          32     40
2  2011-01-01 02:00:00       5          27     32
3  2011-01-01 03:00:00       3          10     13
4  2011-01-01 04:00:00       0           1      1

In [88]:
bike.columns
bike.shape
bike.size
bike.dtypes

datetime      object
casual         int64
registered     int64
count          int64
dtype: object

In [89]:
bike_json.iloc[1]

atemp                      13.635
casual                          8
count                          40
datetime      2011-01-01 01:00:00
holiday                         0
humidity                       80
registered                     32
season                          1
temp                         9.02
weather                         1
windspeed                       0
workingday                      0
Name: 1, dtype: object

In [90]:
bike_json.shape[0]

10886

In [91]:
bike_json.shape[1]

12

In [92]:
bike_json.iloc[0, 0]

14.395

In [93]:
bike_json.iloc[0:3, 9]

0    1
1    1
2    1
Name: weather, dtype: int64

In [94]:
bike_json.iloc[0:3, 2]

0    16
1    40
2    32
Name: count, dtype: int64

In [95]:
bike_json.iloc[0, :2]

atemp     14.395
casual         3
Name: 0, dtype: object

In [96]:
bike_json.iloc[[0], :2]

atemp  casual
0  14.395       3

In [97]:
bike_json.iloc[0, [0, 4]]

atemp      14.395
holiday         0
Name: 0, dtype: object

In [98]:
bike_json.iloc[[0], [0, 4]]

atemp  holiday
0  14.395        0

In [99]:
bike_json.iloc[:2, [0, 4]]

atemp  holiday
0  14.395        0
1  13.635        0

In [100]:
bike_json.loc[[0], ["datetime", "weather"]]

datetime  weather
0 2011-01-01        1

In [101]:
bike_json.loc[:2, ["datetime", "weather"]]

datetime  weather
0 2011-01-01 00:00:00        1
1 2011-01-01 01:00:00        1
2 2011-01-01 02:00:00        1

In [102]:
bike_json.loc[:2, "datetime" : "weather"]

datetime  holiday  humidity  registered  season  temp  weather
0 2011-01-01 00:00:00        0        81          13       1  9.84        1
1 2011-01-01 01:00:00        0        80          32       1  9.02        1
2 2011-01-01 02:00:00        0        80          27       1  9.02        1

In [103]:
nums = [1, 2, 2, 5, 8,8]
len(nums)

6

In [104]:
set(nums)

{1, 2, 5, 8}

In [105]:
list(set(nums))

[8, 1, 2, 5]

In [106]:
np.unique(nums)

array([1, 2, 5, 8])

In [107]:
len(set(nums))

4

In [108]:
len(set(bike_json["weather"]))

4

In [109]:
set(bike_json["weather"])

{1, 2, 3, 4}

In [110]:
sum(nums)

26

In [111]:
min(nums)

1

In [112]:
np.average(nums)

4.333333333333333

In [113]:
np.mean(nums)

4.333333333333333

In [114]:
np.var(nums)

8.222222222222221

In [115]:
np.std(nums)

2.8674417556808756

In [116]:
bike_json["season"].value_counts()

4    2734
3    2733
2    2733
1    2686
Name: season, dtype: int64

In [117]:
bike_json.iloc[:3, 1:3]

casual  count
0       3     16
1       8     40
2       5     32

In [118]:
bike_json.iloc[:3, 1:3].sum(axis=0)

casual    16
count     88
dtype: int64

In [119]:
bike_json.iloc[:3, 1:3].sum(axis=1)

0    19
1    48
2    37
dtype: int64

In [120]:
bike_json.iloc[:3, 1:3].sum()

casual    16
count     88
dtype: int64

In [121]:
bike_json.iloc[:3, 1:3].sum(0)

casual    16
count     88
dtype: int64

In [122]:
pd.crosstab(bike_json["season"], bike_json["holiday"], normalize=1)

holiday         0         1
season                     
1        0.247281  0.228296
2        0.253901  0.154341
3        0.249362  0.308682
4        0.249456  0.308682

In [123]:
bike_json["season"]

0        1
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
        ..
10856    4
10857    4
10858    4
10859    4
10860    4
10861    4
10862    4
10863    4
10864    4
10865    4
10866    4
10867    4
10868    4
10869    4
10870    4
10871    4
10872    4
10873    4
10874    4
10875    4
10876    4
10877    4
10878    4
10879    4
10880    4
10881    4
10882    4
10883    4
10884    4
10885    4
Name: season, Length: 10886, dtype: int64

In [125]:
# bike_json.iloc[:, [1, 12]].groupby("season").mean()

In [126]:
bike_json.loc[:, ["season", "casual"]].groupby("season").mean()


casual
season           
1       15.489576
2       47.446762
3       52.220271
4       28.580834

In [127]:
bike_json.loc[:, ["season", "casual", "registered"]].groupby("season").mean()
# casual 일일대여
# registered 정기대여

casual  registered
season                       
1       15.489576  100.853686
2       47.446762  167.804610
3       52.220271  182.196853
4       28.580834  170.407462

In [128]:
bike_json_sub = bike_json[bike_json.season == 1]

In [129]:
bike_json_sub.head(2)

atemp  casual  count            datetime  holiday  humidity  registered  \
0  14.395       3     16 2011-01-01 00:00:00        0        81          13   
1  13.635       8     40 2011-01-01 01:00:00        0        80          32   

   season  temp  weather  windspeed  workingday  
0       1  9.84        1        0.0           0  
1       1  9.02        1        0.0           0

In [130]:
bike_json_sub.shape

(2686, 12)

In [131]:
set(bike_json_sub.season)

{1}

In [132]:
bike_json_sub2 = bike_json[(bike_json.season == 1) & (bike_json.holiday == 1)]

In [133]:
bike_json_sub2.head(2)

atemp  casual  count            datetime  holiday  humidity  registered  \
372   9.85       1     17 2011-01-17 00:00:00        1        47          16   
373   9.85       1     16 2011-01-17 01:00:00        1        44          15   

     season  temp  weather  windspeed  workingday  
372       1   8.2        2    15.0013           0  
373       1   8.2        2    12.9980           0

In [134]:
set(bike_json_sub2.season)

{1}

In [135]:
bike_json_sub = bike_json.iloc[np.in1d(bike_json.season, [1,2]), :]
set(bike_json_sub.season)

{1, 2}

In [136]:
df = bike_json

In [137]:
df_sub = df[df["season"] == 1]
df_sub.shape

(2686, 12)

In [138]:
df_sub2 = df[(df["season"] == 1) & (df["holiday"] == 1)]
set(df_sub2["season"])

{1}

In [139]:
df_sub3 = df[(df["season"] == 1) | (df["holiday"] == 1)]
set(df_sub3["season"])

{1, 2, 3, 4}

In [140]:
df_sub3.head(3)

atemp  casual  count            datetime  holiday  humidity  registered  \
0  14.395       3     16 2011-01-01 00:00:00        0        81          13   
1  13.635       8     40 2011-01-01 01:00:00        0        80          32   
2  13.635       5     32 2011-01-01 02:00:00        0        80          27   

   season  temp  weather  windspeed  workingday  
0       1  9.84        1        0.0           0  
1       1  9.02        1        0.0           0  
2       1  9.02        1        0.0           0

In [141]:
level = ["A", "B", "C", "D", "F"]
mine = "C"
if mine in level[:1]:
    print("Pass")
elif mine == level[2]:
    print("retake")
else : 
    print("Fail")

retake


In [142]:
listt = ["a", "b", "c"]
for i in listt:
    print(i)

a
b
c


In [143]:
a = [(1,2), (3,4), (5,6)]
for (first, last) in a:
    print(first+ last)

3
7
11


In [144]:
for n in range(10):
    print(n)

0
1
2
3
4
5
6
7
8
9


In [145]:
a = [2, 6,7,8,9]
[num for num in a if num % 2 == 0]

[2, 6, 8]

In [146]:
listt = []
for num in a:
    if num % 2 ==0:
        listt = listt + [num]
listt

[2, 6, 8]